(() => {
  const TOTAL=1025,PAGE=80;
  const regions={kanto:[1,151],johto:[152,251],hoenn:[252,386],sinnoh:[387,493],unova:[494,649],kalos:[650,721],alola:[722,809],galar:[810,905],paldea:[906,1025]};
  const $=selector=>document.querySelector(selector),art=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`,title=value=>value.replaceAll("-"," ").replace(/\b\p{L}/gu,letter=>letter.toUpperCase()),brl=value=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
  const el={grid:$("#grid"),search:$("#search"),region:$("#region-filter"),owned:$("#only-owned"),missing:$("#only-missing"),type:$("#card-type-filter"),trade:$("#trade-filter"),sort:$("#sort-select"),active:$("#active-filters"),result:$("#result-count"),more:$("#load-more"),count:$("#card-count"),value:$("#collection-value"),updated:$("#updated-at"),progress:$("#progress"),bar:$("#progress-bar"),modal:$("#pokemon-modal"),close:$("#close-modal"),image:$("#modal-image"),number:$("#modal-number"),name:$("#modal-name"),details:$("#modal-details"),price:$("#modal-price"),liga:$("#modal-liga")};
  let pokemon=[],selections={},shown=PAGE,onlyOwned=false,onlyMissing=false,timer;
  const inRegion=(id,region)=>region==="all"||(regions[region]&&id>=regions[region][0]&&id<=regions[region][1]);
  const priceOf=card=>card?.price?.currency==="BRL"?Number(card.price.amount)||0:0;
  function cardType(card){if(!card)return"";if(card.cardType)return card.cardType;if(card.variant)return card.variant;if(card.reverseFoil)return"reverse";if(card.foil)return"holo";return"normal"}
  function ligaUrl(card){const n=String(card.liga?.lookupNumber||card.liga?.number||card.number||""),total=String(card.liga?.total||"");const url=new URL("https://www.ligapokemon.com.br/");url.searchParams.set("view","cards/card");url.searchParams.set("card",`${card.liga?.name||card.name} (${n}/${total})`);return url}
  function entries(){const term=el.search.value.trim().toLowerCase(),region=el.region.value,type=el.type.value,trade=el.trade.value;const list=pokemon.filter(p=>{const card=selections[p.id],text=`${p.name} ${card?.name||""} ${card?.set||""} ${card?.number||""}`.toLowerCase(),matchesTrade=trade==="all"||(trade==="trade"?Boolean(card?.tradeWanted):Boolean(card&&!card.tradeWanted));return inRegion(p.id,region)&&(!onlyOwned||card)&&(!onlyMissing||!card)&&(type==="all"||cardType(card)===type)&&matchesTrade&&(!term||text.includes(term))});return list.sort((a,b)=>{const ca=selections[a.id],cb=selections[b.id];switch(el.sort.value){case"name":return a.name.localeCompare(b.name,"pt-BR");case"price-high":return priceOf(cb)-priceOf(ca);case"price-low":return priceOf(ca)-priceOf(cb);case"recent":return new Date(cb?.selectedAt||0)-new Date(ca?.selectedAt||0);default:return a.id-b.id}})}
  function syncToggles(){el.owned.setAttribute("aria-pressed",String(onlyOwned));el.missing.setAttribute("aria-pressed",String(onlyMissing))}
  function resetFilters(){el.search.value="";el.region.value="all";el.type.value="all";el.trade.value="all";el.sort.value="dex";onlyOwned=false;onlyMissing=false;shown=PAGE;syncToggles();render()}
  function renderActiveFilters(){const active=[];if(el.search.value.trim())active.push([`Busca: ${el.search.value.trim()}`,()=>el.search.value=""]);if(el.region.value!=="all")active.push([el.region.options[el.region.selectedIndex].text,()=>el.region.value="all"]);if(el.type.value!=="all")active.push([el.type.options[el.type.selectedIndex].text,()=>el.type.value="all"]);if(el.trade.value!=="all")active.push([el.trade.options[el.trade.selectedIndex].text,()=>el.trade.value="all"]);if(el.sort.value!=="dex")active.push([`Ordem: ${el.sort.options[el.sort.selectedIndex].text}`,()=>el.sort.value="dex"]);if(onlyOwned)active.push(["Só com carta",()=>onlyOwned=false]);if(onlyMissing)active.push(["Sem carta",()=>onlyMissing=false]);el.active.hidden=!active.length;const fragment=document.createDocumentFragment();active.forEach(([label,clear])=>{const button=document.createElement("button");button.type="button";button.textContent=`${label} ×`;button.addEventListener("click",()=>{clear();shown=PAGE;syncToggles();render()});fragment.append(button)});if(active.length>1){const button=document.createElement("button");button.type="button";button.className="clear-filters";button.textContent="Limpar tudo";button.addEventListener("click",resetFilters);fragment.append(button)}el.active.replaceChildren(fragment)}
  function render(){const list=entries(),fragment=document.createDocumentFragment();list.slice(0,shown).forEach(p=>{const card=selections[p.id],button=document.createElement("button");button.type="button";button.className=`pokemon-card${card?" has-card":""}`;button.innerHTML=`<img src="${card?.thumbnail||card?.image||p.art}" alt="${card?`Carta ${card.name}`:p.name}" loading="lazy" decoding="async"><span class="dex-number">#${String(p.id).padStart(4,"0")}</span><span class="pokemon-name">${p.name}</span><span class="card-info">${card?`${card.set} · ${card.number}`:"Ainda não registrado"}</span>${card?'<i class="owned-badge">TCG</i>':""}`;button.addEventListener("click",()=>open(p,card));fragment.append(button)});el.grid.replaceChildren(fragment);el.result.textContent=`${list.length} Pokémon ${onlyOwned?"com carta":onlyMissing?"sem carta":"encontrados"}`;el.more.hidden=list.length<=shown;renderActiveFilters()}
  function open(p,card){el.image.src=card?.image||p.art;el.image.alt=card?`Carta ${card.name}`:p.name;el.number.textContent=`Pokédex #${String(p.id).padStart(4,"0")}`;el.name.textContent=p.name;el.details.textContent=card?`${card.name} · ${card.set} · #${card.number}`:"Este Pokémon ainda não possui uma carta registrada no Master Set.";el.price.textContent=card?.price?.currency==="BRL"?brl(card.price.amount):card?"Preço não informado":"";el.liga.hidden=!card;if(card)el.liga.href=ligaUrl(card);el.modal.showModal()}
  async function load(){try{const [collection,poke]=await Promise.all([fetch("collection.json",{cache:"no-store"}),fetch(`https://pokeapi.co/api/v2/pokemon?limit=${TOTAL}`)]);if(!collection.ok||!poke.ok)throw Error();const saved=await collection.json(),data=await poke.json();selections=saved.selections||{};pokemon=data.results.map(item=>{const id=Number(item.url.match(/\/pokemon\/(\d+)\/$/)[1]);return{id,name:title(item.name),art:art(id)}}).sort((a,b)=>a.id-b.id);const owned=pokemon.filter(p=>selections[p.id]),sum=owned.reduce((total,p)=>total+priceOf(selections[p.id]),0),percent=Math.round(owned.length/TOTAL*100);el.count.textContent=owned.length;el.value.textContent=brl(sum);el.updated.textContent=saved.exportedAt?new Date(saved.exportedAt).toLocaleDateString("pt-BR"):"—";el.progress.textContent=`${owned.length} / ${TOTAL}`;el.bar.style.width=`${percent}%`;render()}catch{el.result.textContent="Não foi possível carregar a Pokédex. Verifique a conexão e recarregue a página."}}
  el.search.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>{shown=PAGE;render()},100)});[el.region,el.type,el.trade,el.sort].forEach(input=>input.addEventListener("change",()=>{shown=PAGE;render()}));el.owned.addEventListener("click",()=>{onlyOwned=!onlyOwned;if(onlyOwned)onlyMissing=false;shown=PAGE;syncToggles();render()});el.missing.addEventListener("click",()=>{onlyMissing=!onlyMissing;if(onlyMissing)onlyOwned=false;shown=PAGE;syncToggles();render()});el.more.addEventListener("click",()=>{shown+=PAGE;render()});el.close.addEventListener("click",()=>el.modal.close());el.modal.addEventListener("click",event=>{if(event.target===el.modal)el.modal.close()});$("#year").textContent=new Date().getFullYear();load();
})();
